alias center="sudo bash ~/docker/enter.sh"
alias cstop="sudo bash ~/docker/stop.sh"
alias crestart="sudo bash ~/docker/restart.sh"
alias cstart="sudo bash ~/docker/start.sh"
alias runit="cmake ..; make; ./main"
